[build]
  base = ""
  publish = "build/"
  command = "CI= npm build"
  environment = { YARN_VERSION = "1.22.4", NODE_ENV = "production", NODE_VERSION = "12" }

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200